# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friends.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import users_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='friends.proto',
  package='',
  serialized_pb='\n\rfriends.proto\x1a\x0busers.proto\"#\n\x11GetFriendsRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\",\n\x12GetFriendsResponse\x12\x16\n\x07\x66riends\x18\x01 \x03(\x0b\x32\x05.User\"8\n\x10\x41\x64\x64\x46riendRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\x12\x14\n\x0c\x66riend_email\x18\x02 \x02(\t\")\n\x11\x41\x64\x64\x46riendResponse\x12\x14\n\x0c\x66riend_added\x18\x01 \x02(\x08\";\n\x13RemoveFriendRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\x12\x14\n\x0c\x66riend_email\x18\x02 \x02(\t\".\n\x14RemoveFriendResponse\x12\x16\n\x0e\x66riend_removed\x18\x01 \x02(\x08')




_GETFRIENDSREQUEST = _descriptor.Descriptor(
  name='GetFriendsRequest',
  full_name='GetFriendsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='GetFriendsRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=65,
)


_GETFRIENDSRESPONSE = _descriptor.Descriptor(
  name='GetFriendsResponse',
  full_name='GetFriendsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friends', full_name='GetFriendsResponse.friends', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=67,
  serialized_end=111,
)


_ADDFRIENDREQUEST = _descriptor.Descriptor(
  name='AddFriendRequest',
  full_name='AddFriendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='AddFriendRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friend_email', full_name='AddFriendRequest.friend_email', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=113,
  serialized_end=169,
)


_ADDFRIENDRESPONSE = _descriptor.Descriptor(
  name='AddFriendResponse',
  full_name='AddFriendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friend_added', full_name='AddFriendResponse.friend_added', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=171,
  serialized_end=212,
)


_REMOVEFRIENDREQUEST = _descriptor.Descriptor(
  name='RemoveFriendRequest',
  full_name='RemoveFriendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='RemoveFriendRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friend_email', full_name='RemoveFriendRequest.friend_email', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=214,
  serialized_end=273,
)


_REMOVEFRIENDRESPONSE = _descriptor.Descriptor(
  name='RemoveFriendResponse',
  full_name='RemoveFriendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friend_removed', full_name='RemoveFriendResponse.friend_removed', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=275,
  serialized_end=321,
)

_GETFRIENDSRESPONSE.fields_by_name['friends'].message_type = users_pb2._USER
DESCRIPTOR.message_types_by_name['GetFriendsRequest'] = _GETFRIENDSREQUEST
DESCRIPTOR.message_types_by_name['GetFriendsResponse'] = _GETFRIENDSRESPONSE
DESCRIPTOR.message_types_by_name['AddFriendRequest'] = _ADDFRIENDREQUEST
DESCRIPTOR.message_types_by_name['AddFriendResponse'] = _ADDFRIENDRESPONSE
DESCRIPTOR.message_types_by_name['RemoveFriendRequest'] = _REMOVEFRIENDREQUEST
DESCRIPTOR.message_types_by_name['RemoveFriendResponse'] = _REMOVEFRIENDRESPONSE

class GetFriendsRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFRIENDSREQUEST

  # @@protoc_insertion_point(class_scope:GetFriendsRequest)

class GetFriendsResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFRIENDSRESPONSE

  # @@protoc_insertion_point(class_scope:GetFriendsResponse)

class AddFriendRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDFRIENDREQUEST

  # @@protoc_insertion_point(class_scope:AddFriendRequest)

class AddFriendResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDFRIENDRESPONSE

  # @@protoc_insertion_point(class_scope:AddFriendResponse)

class RemoveFriendRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMOVEFRIENDREQUEST

  # @@protoc_insertion_point(class_scope:RemoveFriendRequest)

class RemoveFriendResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMOVEFRIENDRESPONSE

  # @@protoc_insertion_point(class_scope:RemoveFriendResponse)


# @@protoc_insertion_point(module_scope)
