# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friends.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='friends.proto',
  package='',
  serialized_pb='\n\rfriends.proto\"#\n\x11GetFriendsRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\"*\n\x12GetFriendsResponse\x12\x14\n\x0c\x66riends_list\x18\x01 \x03(\t')




_GETFRIENDSREQUEST = _descriptor.Descriptor(
  name='GetFriendsRequest',
  full_name='GetFriendsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='GetFriendsRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=52,
)


_GETFRIENDSRESPONSE = _descriptor.Descriptor(
  name='GetFriendsResponse',
  full_name='GetFriendsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friends_list', full_name='GetFriendsResponse.friends_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['GetFriendsRequest'] = _GETFRIENDSREQUEST
DESCRIPTOR.message_types_by_name['GetFriendsResponse'] = _GETFRIENDSRESPONSE

class GetFriendsRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFRIENDSREQUEST

  # @@protoc_insertion_point(class_scope:GetFriendsRequest)

class GetFriendsResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFRIENDSRESPONSE

  # @@protoc_insertion_point(class_scope:GetFriendsResponse)


# @@protoc_insertion_point(module_scope)
