# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: games.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='games.proto',
  package='',
  serialized_pb='\n\x0bgames.proto\"\x1d\n\x0fGameInfoRequest\x12\n\n\x02id\x18\x01 \x02(\x05\";\n\rGameInfoReply\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07players\x18\x02 \x03(\x05\x12\r\n\x05\x62oard\x18\x03 \x03(\x05\"\x1d\n\nCreateGame\x12\x0f\n\x07players\x18\x01 \x03(\x05\"D\n\nPlayerMove\x12\x0e\n\x06gameId\x18\x01 \x02(\x05\x12\x10\n\x08playerId\x18\x02 \x02(\x05\x12\t\n\x01x\x18\x03 \x02(\x05\x12\t\n\x01y\x18\x04 \x02(\x05\"\x17\n\x07\x46\x61ilure\x12\x0c\n\x04what\x18\x01 \x02(\tB\x0e\x42\x0cGameprotocol')




_GAMEINFOREQUEST = _descriptor.Descriptor(
  name='GameInfoRequest',
  full_name='GameInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GameInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=44,
)


_GAMEINFOREPLY = _descriptor.Descriptor(
  name='GameInfoReply',
  full_name='GameInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GameInfoReply.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players', full_name='GameInfoReply.players', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='board', full_name='GameInfoReply.board', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=105,
)


_CREATEGAME = _descriptor.Descriptor(
  name='CreateGame',
  full_name='CreateGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='players', full_name='CreateGame.players', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=107,
  serialized_end=136,
)


_PLAYERMOVE = _descriptor.Descriptor(
  name='PlayerMove',
  full_name='PlayerMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='PlayerMove.gameId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playerId', full_name='PlayerMove.playerId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='PlayerMove.x', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='PlayerMove.y', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=138,
  serialized_end=206,
)


_FAILURE = _descriptor.Descriptor(
  name='Failure',
  full_name='Failure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='what', full_name='Failure.what', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=208,
  serialized_end=231,
)

DESCRIPTOR.message_types_by_name['GameInfoRequest'] = _GAMEINFOREQUEST
DESCRIPTOR.message_types_by_name['GameInfoReply'] = _GAMEINFOREPLY
DESCRIPTOR.message_types_by_name['CreateGame'] = _CREATEGAME
DESCRIPTOR.message_types_by_name['PlayerMove'] = _PLAYERMOVE
DESCRIPTOR.message_types_by_name['Failure'] = _FAILURE

class GameInfoRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMEINFOREQUEST

  # @@protoc_insertion_point(class_scope:GameInfoRequest)

class GameInfoReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMEINFOREPLY

  # @@protoc_insertion_point(class_scope:GameInfoReply)

class CreateGame(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEGAME

  # @@protoc_insertion_point(class_scope:CreateGame)

class PlayerMove(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERMOVE

  # @@protoc_insertion_point(class_scope:PlayerMove)

class Failure(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FAILURE

  # @@protoc_insertion_point(class_scope:Failure)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'B\014Gameprotocol')
# @@protoc_insertion_point(module_scope)
