# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lobbies.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import users_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lobbies.proto',
  package='',
  serialized_pb='\n\rlobbies.proto\x1a\x0busers.proto\"j\n\x06Lobbyn\x12\x0f\n\x07lobbyId\x18\x01 \x02(\x05\x12\x14\n\x05owner\x18\x02 \x02(\x0b\x32\x05.User\x12\'\n\x0clobbymembers\x18\x03 \x03(\x0b\x32\x11.LobbyMembershipn\x12\x10\n\x08gameType\x18\x04 \x02(\x05\"@\n\x10LobbyMembershipn\x12\x13\n\x04user\x18\x01 \x02(\x0b\x32\x05.User\x12\x17\n\x06status\x18\x02 \x02(\t:\x07Invited\"6\n\x12\x43reateLobbyRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\x12\x10\n\x08gameType\x18\x02 \x02(\x05\"&\n\x13\x43reateLobbyResponse\x12\x0f\n\x07lobbyId\x18\x01 \x02(\x05\"%\n\x13GetLobbyListRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\"0\n\x14GetLobbyListResponse\x12\x18\n\x07lobbies\x18\x01 \x03(\x0b\x32\x07.Lobbyn\"\'\n\x14GetLobbyStateRequest\x12\x0f\n\x07lobbyId\x18\x01 \x02(\x05\"/\n\x15GetLobbyStateResponse\x12\x16\n\x05lobby\x18\x01 \x02(\x0b\x32\x07.Lobbyn\"K\n\x18\x41nswerLobbyInviteRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\x12\x0f\n\x07lobbyId\x18\x02 \x02(\x05\x12\x0e\n\x06\x61nswer\x18\x03 \x02(\t\"+\n\x19\x41nswerLobbyInviteResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x02(\x08\"L\n\x12InviteLobbyRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\x12\x0f\n\x07lobbyId\x18\x02 \x02(\x05\x12\x15\n\rinvite_emails\x18\x03 \x03(\t\".\n\x13InviteLobbyResponse\x12\x17\n\x0f\x66riends_invited\x18\x01 \x02(\x08\"5\n\x12RemoveLobbyRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\x12\x0f\n\x07lobbyId\x18\x02 \x02(\x05\",\n\x13RemoveLobbyResponse\x12\x15\n\rlobby_removed\x18\x01 \x02(\x08\"3\n\x10StartGameRequest\x12\x0e\n\x06userId\x18\x01 \x02(\x05\x12\x0f\n\x07lobbyId\x18\x02 \x02(\x05\"&\n\x11StartGameResponse\x12\x11\n\tisCreated\x18\x01 \x02(\x08')




_LOBBYN = _descriptor.Descriptor(
  name='Lobbyn',
  full_name='Lobbyn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lobbyId', full_name='Lobbyn.lobbyId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='Lobbyn.owner', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobbymembers', full_name='Lobbyn.lobbymembers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameType', full_name='Lobbyn.gameType', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=136,
)


_LOBBYMEMBERSHIPN = _descriptor.Descriptor(
  name='LobbyMembershipn',
  full_name='LobbyMembershipn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='LobbyMembershipn.user', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='LobbyMembershipn.status', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("Invited", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=138,
  serialized_end=202,
)


_CREATELOBBYREQUEST = _descriptor.Descriptor(
  name='CreateLobbyRequest',
  full_name='CreateLobbyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='CreateLobbyRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameType', full_name='CreateLobbyRequest.gameType', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=204,
  serialized_end=258,
)


_CREATELOBBYRESPONSE = _descriptor.Descriptor(
  name='CreateLobbyResponse',
  full_name='CreateLobbyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lobbyId', full_name='CreateLobbyResponse.lobbyId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=260,
  serialized_end=298,
)


_GETLOBBYLISTREQUEST = _descriptor.Descriptor(
  name='GetLobbyListRequest',
  full_name='GetLobbyListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='GetLobbyListRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=300,
  serialized_end=337,
)


_GETLOBBYLISTRESPONSE = _descriptor.Descriptor(
  name='GetLobbyListResponse',
  full_name='GetLobbyListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lobbies', full_name='GetLobbyListResponse.lobbies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=339,
  serialized_end=387,
)


_GETLOBBYSTATEREQUEST = _descriptor.Descriptor(
  name='GetLobbyStateRequest',
  full_name='GetLobbyStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lobbyId', full_name='GetLobbyStateRequest.lobbyId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=389,
  serialized_end=428,
)


_GETLOBBYSTATERESPONSE = _descriptor.Descriptor(
  name='GetLobbyStateResponse',
  full_name='GetLobbyStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lobby', full_name='GetLobbyStateResponse.lobby', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=430,
  serialized_end=477,
)


_ANSWERLOBBYINVITEREQUEST = _descriptor.Descriptor(
  name='AnswerLobbyInviteRequest',
  full_name='AnswerLobbyInviteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='AnswerLobbyInviteRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobbyId', full_name='AnswerLobbyInviteRequest.lobbyId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer', full_name='AnswerLobbyInviteRequest.answer', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=479,
  serialized_end=554,
)


_ANSWERLOBBYINVITERESPONSE = _descriptor.Descriptor(
  name='AnswerLobbyInviteResponse',
  full_name='AnswerLobbyInviteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='AnswerLobbyInviteResponse.answer', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=556,
  serialized_end=599,
)


_INVITELOBBYREQUEST = _descriptor.Descriptor(
  name='InviteLobbyRequest',
  full_name='InviteLobbyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='InviteLobbyRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobbyId', full_name='InviteLobbyRequest.lobbyId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invite_emails', full_name='InviteLobbyRequest.invite_emails', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=601,
  serialized_end=677,
)


_INVITELOBBYRESPONSE = _descriptor.Descriptor(
  name='InviteLobbyResponse',
  full_name='InviteLobbyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friends_invited', full_name='InviteLobbyResponse.friends_invited', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=679,
  serialized_end=725,
)


_REMOVELOBBYREQUEST = _descriptor.Descriptor(
  name='RemoveLobbyRequest',
  full_name='RemoveLobbyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='RemoveLobbyRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobbyId', full_name='RemoveLobbyRequest.lobbyId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=727,
  serialized_end=780,
)


_REMOVELOBBYRESPONSE = _descriptor.Descriptor(
  name='RemoveLobbyResponse',
  full_name='RemoveLobbyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lobby_removed', full_name='RemoveLobbyResponse.lobby_removed', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=782,
  serialized_end=826,
)


_STARTGAMEREQUEST = _descriptor.Descriptor(
  name='StartGameRequest',
  full_name='StartGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='StartGameRequest.userId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobbyId', full_name='StartGameRequest.lobbyId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=828,
  serialized_end=879,
)


_STARTGAMERESPONSE = _descriptor.Descriptor(
  name='StartGameResponse',
  full_name='StartGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isCreated', full_name='StartGameResponse.isCreated', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=881,
  serialized_end=919,
)

_LOBBYN.fields_by_name['owner'].message_type = users_pb2._USER
_LOBBYN.fields_by_name['lobbymembers'].message_type = _LOBBYMEMBERSHIPN
_LOBBYMEMBERSHIPN.fields_by_name['user'].message_type = users_pb2._USER
_GETLOBBYLISTRESPONSE.fields_by_name['lobbies'].message_type = _LOBBYN
_GETLOBBYSTATERESPONSE.fields_by_name['lobby'].message_type = _LOBBYN
DESCRIPTOR.message_types_by_name['Lobbyn'] = _LOBBYN
DESCRIPTOR.message_types_by_name['LobbyMembershipn'] = _LOBBYMEMBERSHIPN
DESCRIPTOR.message_types_by_name['CreateLobbyRequest'] = _CREATELOBBYREQUEST
DESCRIPTOR.message_types_by_name['CreateLobbyResponse'] = _CREATELOBBYRESPONSE
DESCRIPTOR.message_types_by_name['GetLobbyListRequest'] = _GETLOBBYLISTREQUEST
DESCRIPTOR.message_types_by_name['GetLobbyListResponse'] = _GETLOBBYLISTRESPONSE
DESCRIPTOR.message_types_by_name['GetLobbyStateRequest'] = _GETLOBBYSTATEREQUEST
DESCRIPTOR.message_types_by_name['GetLobbyStateResponse'] = _GETLOBBYSTATERESPONSE
DESCRIPTOR.message_types_by_name['AnswerLobbyInviteRequest'] = _ANSWERLOBBYINVITEREQUEST
DESCRIPTOR.message_types_by_name['AnswerLobbyInviteResponse'] = _ANSWERLOBBYINVITERESPONSE
DESCRIPTOR.message_types_by_name['InviteLobbyRequest'] = _INVITELOBBYREQUEST
DESCRIPTOR.message_types_by_name['InviteLobbyResponse'] = _INVITELOBBYRESPONSE
DESCRIPTOR.message_types_by_name['RemoveLobbyRequest'] = _REMOVELOBBYREQUEST
DESCRIPTOR.message_types_by_name['RemoveLobbyResponse'] = _REMOVELOBBYRESPONSE
DESCRIPTOR.message_types_by_name['StartGameRequest'] = _STARTGAMEREQUEST
DESCRIPTOR.message_types_by_name['StartGameResponse'] = _STARTGAMERESPONSE

class Lobbyn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOBBYN

  # @@protoc_insertion_point(class_scope:Lobbyn)

class LobbyMembershipn(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOBBYMEMBERSHIPN

  # @@protoc_insertion_point(class_scope:LobbyMembershipn)

class CreateLobbyRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATELOBBYREQUEST

  # @@protoc_insertion_point(class_scope:CreateLobbyRequest)

class CreateLobbyResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATELOBBYRESPONSE

  # @@protoc_insertion_point(class_scope:CreateLobbyResponse)

class GetLobbyListRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETLOBBYLISTREQUEST

  # @@protoc_insertion_point(class_scope:GetLobbyListRequest)

class GetLobbyListResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETLOBBYLISTRESPONSE

  # @@protoc_insertion_point(class_scope:GetLobbyListResponse)

class GetLobbyStateRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETLOBBYSTATEREQUEST

  # @@protoc_insertion_point(class_scope:GetLobbyStateRequest)

class GetLobbyStateResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETLOBBYSTATERESPONSE

  # @@protoc_insertion_point(class_scope:GetLobbyStateResponse)

class AnswerLobbyInviteRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANSWERLOBBYINVITEREQUEST

  # @@protoc_insertion_point(class_scope:AnswerLobbyInviteRequest)

class AnswerLobbyInviteResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANSWERLOBBYINVITERESPONSE

  # @@protoc_insertion_point(class_scope:AnswerLobbyInviteResponse)

class InviteLobbyRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVITELOBBYREQUEST

  # @@protoc_insertion_point(class_scope:InviteLobbyRequest)

class InviteLobbyResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVITELOBBYRESPONSE

  # @@protoc_insertion_point(class_scope:InviteLobbyResponse)

class RemoveLobbyRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMOVELOBBYREQUEST

  # @@protoc_insertion_point(class_scope:RemoveLobbyRequest)

class RemoveLobbyResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMOVELOBBYRESPONSE

  # @@protoc_insertion_point(class_scope:RemoveLobbyResponse)

class StartGameRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STARTGAMEREQUEST

  # @@protoc_insertion_point(class_scope:StartGameRequest)

class StartGameResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STARTGAMERESPONSE

  # @@protoc_insertion_point(class_scope:StartGameResponse)


# @@protoc_insertion_point(module_scope)
