# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import base_pb2
import users_pb2
import lobbies_pb2
import games_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='protocol',
  serialized_pb='\n\x0eprotocol.proto\x12\x08protocol\x1a\nbase.proto\x1a\x0busers.proto\x1a\rlobbies.proto\x1a\x0bgames.protoB$\n\"com.quizzingbricks.common.protocol')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\"com.quizzingbricks.common.protocol')
# @@protoc_insertion_point(module_scope)
