# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import base_pb2
import users_pb2
import lobbies_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='protocol.proto',
  package='protocol',
  serialized_pb='\n\x0eprotocol.proto\x12\x08protocol\x1a\nbase.proto\x1a\x0busers.proto\x1a\rlobbies.protoB$\n\"com.quizzingbricks.common.protocol')




# @@protoc_insertion_point(module_scope)
