// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lobbies.proto

public final class Lobbies {
  private Lobbies() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CreateLobbyRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userId = 1;
    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();

    // required int32 gameType = 2;
    /**
     * <code>required int32 gameType = 2;</code>
     */
    boolean hasGameType();
    /**
     * <code>required int32 gameType = 2;</code>
     */
    int getGameType();
  }
  /**
   * Protobuf type {@code CreateLobbyRequest}
   */
  public static final class CreateLobbyRequest extends
      com.google.protobuf.GeneratedMessage
      implements CreateLobbyRequestOrBuilder {
    // Use CreateLobbyRequest.newBuilder() to construct.
    private CreateLobbyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreateLobbyRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreateLobbyRequest defaultInstance;
    public static CreateLobbyRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CreateLobbyRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreateLobbyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gameType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Lobbies.internal_static_CreateLobbyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Lobbies.internal_static_CreateLobbyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Lobbies.CreateLobbyRequest.class, Lobbies.CreateLobbyRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CreateLobbyRequest> PARSER =
        new com.google.protobuf.AbstractParser<CreateLobbyRequest>() {
      public CreateLobbyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateLobbyRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreateLobbyRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // required int32 gameType = 2;
    public static final int GAMETYPE_FIELD_NUMBER = 2;
    private int gameType_;
    /**
     * <code>required int32 gameType = 2;</code>
     */
    public boolean hasGameType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 gameType = 2;</code>
     */
    public int getGameType() {
      return gameType_;
    }

    private void initFields() {
      userId_ = 0;
      gameType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGameType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, gameType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gameType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Lobbies.CreateLobbyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lobbies.CreateLobbyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lobbies.CreateLobbyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lobbies.CreateLobbyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lobbies.CreateLobbyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Lobbies.CreateLobbyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Lobbies.CreateLobbyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Lobbies.CreateLobbyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Lobbies.CreateLobbyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Lobbies.CreateLobbyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Lobbies.CreateLobbyRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreateLobbyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Lobbies.CreateLobbyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Lobbies.internal_static_CreateLobbyRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Lobbies.internal_static_CreateLobbyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Lobbies.CreateLobbyRequest.class, Lobbies.CreateLobbyRequest.Builder.class);
      }

      // Construct using Lobbies.CreateLobbyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        gameType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Lobbies.internal_static_CreateLobbyRequest_descriptor;
      }

      public Lobbies.CreateLobbyRequest getDefaultInstanceForType() {
        return Lobbies.CreateLobbyRequest.getDefaultInstance();
      }

      public Lobbies.CreateLobbyRequest build() {
        Lobbies.CreateLobbyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Lobbies.CreateLobbyRequest buildPartial() {
        Lobbies.CreateLobbyRequest result = new Lobbies.CreateLobbyRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gameType_ = gameType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Lobbies.CreateLobbyRequest) {
          return mergeFrom((Lobbies.CreateLobbyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Lobbies.CreateLobbyRequest other) {
        if (other == Lobbies.CreateLobbyRequest.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasGameType()) {
          setGameType(other.getGameType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasGameType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Lobbies.CreateLobbyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Lobbies.CreateLobbyRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userId = 1;
      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // required int32 gameType = 2;
      private int gameType_ ;
      /**
       * <code>required int32 gameType = 2;</code>
       */
      public boolean hasGameType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 gameType = 2;</code>
       */
      public int getGameType() {
        return gameType_;
      }
      /**
       * <code>required int32 gameType = 2;</code>
       */
      public Builder setGameType(int value) {
        bitField0_ |= 0x00000002;
        gameType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gameType = 2;</code>
       */
      public Builder clearGameType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gameType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CreateLobbyRequest)
    }

    static {
      defaultInstance = new CreateLobbyRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CreateLobbyRequest)
  }

  public interface CreateLobbyResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 lobbyId = 1;
    /**
     * <code>required int32 lobbyId = 1;</code>
     */
    boolean hasLobbyId();
    /**
     * <code>required int32 lobbyId = 1;</code>
     */
    int getLobbyId();
  }
  /**
   * Protobuf type {@code CreateLobbyResponse}
   *
   * <pre>
   * lobby id
   * </pre>
   */
  public static final class CreateLobbyResponse extends
      com.google.protobuf.GeneratedMessage
      implements CreateLobbyResponseOrBuilder {
    // Use CreateLobbyResponse.newBuilder() to construct.
    private CreateLobbyResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreateLobbyResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreateLobbyResponse defaultInstance;
    public static CreateLobbyResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CreateLobbyResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreateLobbyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lobbyId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Lobbies.internal_static_CreateLobbyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Lobbies.internal_static_CreateLobbyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Lobbies.CreateLobbyResponse.class, Lobbies.CreateLobbyResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CreateLobbyResponse> PARSER =
        new com.google.protobuf.AbstractParser<CreateLobbyResponse>() {
      public CreateLobbyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateLobbyResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreateLobbyResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 lobbyId = 1;
    public static final int LOBBYID_FIELD_NUMBER = 1;
    private int lobbyId_;
    /**
     * <code>required int32 lobbyId = 1;</code>
     */
    public boolean hasLobbyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 lobbyId = 1;</code>
     */
    public int getLobbyId() {
      return lobbyId_;
    }

    private void initFields() {
      lobbyId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLobbyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, lobbyId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, lobbyId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Lobbies.CreateLobbyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lobbies.CreateLobbyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lobbies.CreateLobbyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lobbies.CreateLobbyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lobbies.CreateLobbyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Lobbies.CreateLobbyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Lobbies.CreateLobbyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Lobbies.CreateLobbyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Lobbies.CreateLobbyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Lobbies.CreateLobbyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Lobbies.CreateLobbyResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreateLobbyResponse}
     *
     * <pre>
     * lobby id
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Lobbies.CreateLobbyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Lobbies.internal_static_CreateLobbyResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Lobbies.internal_static_CreateLobbyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Lobbies.CreateLobbyResponse.class, Lobbies.CreateLobbyResponse.Builder.class);
      }

      // Construct using Lobbies.CreateLobbyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lobbyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Lobbies.internal_static_CreateLobbyResponse_descriptor;
      }

      public Lobbies.CreateLobbyResponse getDefaultInstanceForType() {
        return Lobbies.CreateLobbyResponse.getDefaultInstance();
      }

      public Lobbies.CreateLobbyResponse build() {
        Lobbies.CreateLobbyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Lobbies.CreateLobbyResponse buildPartial() {
        Lobbies.CreateLobbyResponse result = new Lobbies.CreateLobbyResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lobbyId_ = lobbyId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Lobbies.CreateLobbyResponse) {
          return mergeFrom((Lobbies.CreateLobbyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Lobbies.CreateLobbyResponse other) {
        if (other == Lobbies.CreateLobbyResponse.getDefaultInstance()) return this;
        if (other.hasLobbyId()) {
          setLobbyId(other.getLobbyId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLobbyId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Lobbies.CreateLobbyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Lobbies.CreateLobbyResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 lobbyId = 1;
      private int lobbyId_ ;
      /**
       * <code>required int32 lobbyId = 1;</code>
       */
      public boolean hasLobbyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 lobbyId = 1;</code>
       */
      public int getLobbyId() {
        return lobbyId_;
      }
      /**
       * <code>required int32 lobbyId = 1;</code>
       */
      public Builder setLobbyId(int value) {
        bitField0_ |= 0x00000001;
        lobbyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lobbyId = 1;</code>
       */
      public Builder clearLobbyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lobbyId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CreateLobbyResponse)
    }

    static {
      defaultInstance = new CreateLobbyResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CreateLobbyResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateLobbyRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateLobbyRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateLobbyResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreateLobbyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlobbies.proto\"6\n\022CreateLobbyRequest\022\016\n" +
      "\006userId\030\001 \002(\005\022\020\n\010gameType\030\002 \002(\005\"&\n\023Creat" +
      "eLobbyResponse\022\017\n\007lobbyId\030\001 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CreateLobbyRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CreateLobbyRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CreateLobbyRequest_descriptor,
              new java.lang.String[] { "UserId", "GameType", });
          internal_static_CreateLobbyResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CreateLobbyResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CreateLobbyResponse_descriptor,
              new java.lang.String[] { "LobbyId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
